# CNN (Convolutiona Neural Network)

A Convolutional Neural Network (ConvNet/CNN) is
- a Deep Learning algorithm
- a neural network with convolution

**jargon alert**
- convolution
- filters
- pooling
- padding
- stride

**Requirements:** There are only 2 requirements
1. multiplication
2. addition

### Basic understanding

1. If I have an imput image and I use gaussian filter(kernel), I'll get a blurred image
2. If I have an imput image and I use edge detection filter(kernel), I'll get a sharp image

![convolution](images/convolution.JPG)

So, the convolve operation between the input image and filter to get the final image is called convolution.

$inputImage*filter=outputImage$ here, $*$ sign is the convolve operation

**what makes the 2 convoltuions different?**

Ans: filter

#### Example

To determine the output size: $ \frac{n-f+2p}{s} + 1 $

where,
- n = input image size(height/width)
- f = filter size
- p = padding
- s = stride

input image will not always be square whereas, kernel/filter is square by convention

In [2]:
import numpy as np

In [28]:
np.random.seed(1)
inputImage = np.random.randint(0, 10, size=(4,4))
filterr = np.random.randint(0, 3, size=(2,2))
output = []

# output image size calculation
n, f, p, s = 4, 2, 0, 1
outputSize = int((n - f + 2*p)/s + 1)

print(f"input image: \n{inputImage}")
print(f"filter: \n{filterr}")

# convolve operation
for r in range(len(inputImage)-1):
    for c in range(len(inputImage)-1):
        # 2 requirement as stated above: multiply, add
        ans = np.multiply(inputImage[r:r+2, c:c+2], filterr).sum()
        output.append(ans)

outputImage = np.array(output)
outputImage = outputImage.reshape(outputSize, outputSize)
print(f"output image: \n{outputImage}")

input image: 
[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]
 [5 2 4 2]]
filter: 
[[0 1]
 [1 2]]
output image: 
[[ 8 11 20]
 [24 14 17]
 [18 12 12]]


### Q: What if we want the output image to be same size as input image?

Ans: We add padding around the input image.

### Q: So, what is filter actually doing?

Ans: It slides along the input image to find a pattern. If it founds similiarity, it gives high value otherwise low value.

## Basic CNN architecture

![cnn](images/cnn.JPG)

### Q: What is pooling?

- Pooling is added after the convolutiona layer.
- At a high level, pooling is downsampling.
- Types of pooling:
    - max pooling
    - average pooling
- We define filter size & stride here also. But in here, when filter slides along the output image, it takes the maximum value(`max pooling`) withing its range instead of doing element-wise mulplication and addition

![pooling](images/pooling.JPG)

Hyperparameters in pooling:
1. filter/pool size
2. stride

#### Why we use it?

- It shrinks the image and we have less data for computation
- convolution is a pattern finder(the highest number is the best matching location)

#### Why convolution followed by pooling?

